language: python
install:
- pip install -r ./requirements.txt
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
env:
  global:
  - MUVI_SCRATCH: ~/
script:
  - python -m unittest discover ./tests/