language: python
before_install:
- sudo apt-get update
- sudo apt-get install ffmpeg
- sudo apt-get install frei0r-plugins
install:
- pip install -r ./requirements.txt
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
  - python: 3.9
env:
  global:
  - MUVI_SCRATCH: ~/
script:
  - coverage run --concurrency=multiprocessing -m unittest discover test/
  - coverage combine
after_success:
  - coveralls